### PR TITLE
add autocompletion to package list

### PR DESCRIPTION
**Pull request by mwarning**
The package list will autocomplete packages and only allow known
packages.

### CODE REVIEW

**Comment by mwarning** [comment]
A source for the package list is missing.

**Comment by aparcar** [comment]
> A source for the package list is missing.

Please find a target specific index at the following URL

    http://aparcar.github.io/openwrt-packages-index/{target}/index.json

Working URL examples:

http://aparcar.github.io/openwrt-packages-index/ath79/generic/index.json
http://aparcar.github.io/openwrt-packages-index/ath79/generic/index.json.gz

If more than just the names are needed, like a description, maintainer or latest version, please load one of the following:
 
http://aparcar.github.io/openwrt-packages-index/ath79/generic/manifest.json
http://aparcar.github.io/openwrt-packages-index/ath79/generic/manifest.json.gz

**Comment by mwarning** [comment]
@aparcar the links are all dead :/

**Comment by aparcar** [comment]
Updated, sorry

**Comment by mwarning** [comment]
We probably need the information what packages are required (essential packages / not removeable) and which are selected already but optional and which are available.

**Comment by mwarning** [comment]
@aparcar we need to decide from where the package lists come from. What is needed is the default package list and the list of packages that can be chosen from.

**Comment by mwarning** [comment]
I have introduced a new setting asu_packages, but it would make sense to use some sub folder of asa_url. Any preference on the sub folder path?

**Comment by aparcar** [comment]
Why not https://aparcar.github.io/openwrt-json/?

To support multiple versions I have to change the structure of openwrt-json, we could stick to the official structure of `snapshots/` and `releases/<version>`, what do you think?

**Comment by mwarning** [comment]
ok

**Comment by mwarning** [comment]
@aparcar I have set it to `config.asu_url + '/openwrt-json/' + target + '/index.json'`, which mightnot sit quite right with the eye..

**Comment by mwarning** [comment]
Allowing a minus in front of package names is a bit of a hassle to implement.
Also, it is hard for the user to see what packages are there to be removed.
Thus, it might be more elegant, to show all packages.

**Comment by mwarning** [comment]
I merge this so we can improve on it. Otherwise it will take too much time.

**Pull request merged**
