### PR TITLE
Use updated server API

### PR DESCRIPTION
**Pull request by aparcar**
Instead of returning the full url to the binary directory now returns
`bin_dir` only. This is possible as `asu_url` is already defined
locally. This approach allows devices not using https to download
content unencrypted, meaning the server response does not delegate the
protocol.

In addition a boolean value is returned stating if a buildlog was
created, which is shown in case of failures.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
This is an implementation of the logic, it doesn't look very pretty.

**Comment by mwarning** [comment]
We should target this at some development branch. So people will not be presented with a in-development GUI.

**Comment by aparcar** [comment]
What is the difference between the `server_url` branch and some development branch?

**Comment by mwarning** [comment]
@aparcar the server_url branch would be for a specific feature, a development branch for multiple features that are in development.
But since the server_url is local to this project, we don't really need a development branch. But then we should not merge it until the feature is finished.

**Comment by aparcar** [comment]
We should remove the `alert()` functions and replace them with proper notifications. Once this is done the notification could simply include the buildlog. Would you be up for doing that?

**Comment by mwarning** [comment]
I think so, but I cannot give a guarantee for the timeline.

**Comment by aparcar** [comment]
Bump? I guess we can also merge this as alert isn"t that bad after all...

**Comment by mwarning** [comment]
I thought I wait until I get time to make the gui elements nice looking.
But that might hold of this PR too much.

**Pull request merged**
