### PR TITLE
use upstream like json files

### PR DESCRIPTION
**Pull request by aparcar**
This PR simplifies the code by using a data structure similar to the
OpenWrt upstream files. Ideally OpenWrt offers at some point files
similar to names-<version>.json.

The missing bit is that multiple files files containing images of a
release should be loaded, however always just the selected one and on
demand, so not all JSON files if only the latest version is selected. I
tried to implement this, however ended up in the *callback hell* (as I
learned today) - so please don't hesitate helping me here.

I accidentally used an autoformat tool called `js-beautify` which changed
parts of the code indention without changing its functionality, however
as this is more a RFC than an actual PR I did not fixed it afterwards.

Using this structure would also work together with the new *image on
demand* service I'm working on[0].

[0]: https://github.com/aparcar/sasu

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
image

**Comment by aparcar** [comment]
Having multiple release files on demand also allows to keep things small while supporting more and more releases, the single file approach eventually bloats up the initial data loading.

**Comment by mwarning** [comment]
Thanks or the proposal.

A few things:
- the button labels are very cryptic now. Imo, the current approach using sysupgrade/factory/.. buttons with extra tagging (if necessary) is better.
- I would put the versions.json into config.json and use file names. This is simpler and more straight forward:
```
  var config = {
  // Default language, see i18n.js
  language: 'en',
  // Show help text for images
  showHelp: true,
  // File to get data from
  versions: {
   "SNAPSHOT":  "names-SNAPSHOT.json",
   "19.07.1": "names-19.07.1.json"
  }
};
```

**Comment by aparcar** [comment]
The buttons can should have additional descriptions however better based on type not filename, don't you think?

I'm okay with the rest, are you up to do the async magic?

**Comment by mwarning** [comment]
@aparcar I do not think the type field of the OpenWrt json output has enough information for this image selector yet. I would like to keep the heuristic for now.

Please have a look at the current state of the code and let me know if that is something we can continue on.

**Comment by aparcar** [comment]
In fine with the current heuristic, I'm just caring about the data structure right now

**Comment by mwarning** [comment]
Is that ok? https://github.com/mwarning/yet_another_firmware_selector/blob/master/names-SNAPSHOT.json

**Comment by mwarning** [comment]
> I'm okay with the rest, are you up to do the async magic?
Here is the gist of it:
```
mkdir tmp
rsync -avm  --include='*.json' --include='*/' --exclude='*' 'rsync://downloads.openwrt.org/downloads/snapshots/targets/' tmp/
```

**Pull request closed without merging**
